<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>AquaTrack</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\LogoOnly.png" />
    <None Remove="Images\WaterHomepageBG.png" />
    <None Remove="Images\WaterUsageBG.png" />
    <None Remove="Images\water_background.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\AquatrackLogo.png" />
    <Resource Include="Images\LogoOnly.png" />
    <Resource Include="Images\WaterHomepageBG.png" />
    <Resource Include="Images\WaterUsageBG.png" />
    <Resource Include="Images\water_background.jpg" />
  </ItemGroup>

</Project>
